/**
 * Theme: LED — Giải pháp chiếu sáng đèn LED
 * Cùng layout/UI với Solar; chỉ khác nội dung, màu & hình ảnh
 */
window.SiteThemes = window.SiteThemes || {};
window.SiteThemes.led = {
  id: 'led',
  colors: {
    primary: '#0B3D91',
    primaryHover: '#082e6e',
    secondary: '#081C3A',
    accent: '#22D3EE',
  },
  meta: {
    title: 'Đèn LED | Giải pháp chiếu sáng hiện đại | Solar Miền Nam',
    description:
      'Giải pháp chiếu sáng LED tiết kiệm điện cho nhà xưởng, văn phòng, đường phố, khách sạn và công trình dân dụng. Tư vấn – thiết kế – thi công trọn gói.',
  },
  industryTitle: 'ĐÈN LED',
  brand: { name: 'Solar', sub: 'Miền Nam' },
  brandIcon: 'bulb',
  projectMetaLabel: 'Quy mô',
  hero: {
    slides: [
      {
        src: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=3840&q=90',
        alt: 'Văn phòng hiện đại với hệ thống đèn LED panel',
      },
      {
        src: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&w=3840&q=90',
        alt: 'Nhà xưởng chiếu sáng bằng đèn LED highbay',
      },
      {
        src: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=3840&q=90',
        alt: 'Khách sạn – không gian sảnh chiếu sáng LED ấm áp',
      },
      {
        src: 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=3840&q=90',
        alt: 'Đường phố về đêm với đèn LED đường',
      },
    ],
    title: ['GIẢI PHÁP', 'CHIẾU SÁNG', 'ĐÈN LED'],
    titleAccentIndex: 1,
    desc: 'Chiếu sáng hiện đại, tiết kiệm điện và bền bỉ cho nhà xưởng, văn phòng, khách sạn và đô thị.',
    ctaPrimary: 'Liên hệ Zalo',
    ctaSecondary: 'Xem sản phẩm',
  },
  about: {
    label: 'VỀ CHÚNG TÔI',
    titleLines: ['CHIẾU SÁNG THÔNG MINH CHO ', 'MỌI CÔNG TRÌNH'],
    titleAccentIndex: 1,
    desc: 'Với kinh nghiệm triển khai chiếu sáng LED cho nhà xưởng, văn phòng và đô thị, Solar Miền Nam mang đến giải pháp tiết kiệm điện, bền bỉ và tối ưu chi phí vận hành.',
    highlight: 'Chúng tôi cam kết đồng hành cùng khách hàng từ tư vấn, thiết kế đến thi công và bảo trì — nâng tầm không gian và hiệu quả năng lượng.',
    image: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1600&q=90',
    imageAlt: 'Không gian nội thất hiện đại với hệ thống đèn LED',
    bg: {
      src: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=3840&q=90',
      overlay: 0.96,
      tone: 'sky',
      pattern: 'dots-circuit',
    },
    features: [],
    cta: 'XEM THÊM',
    ctaHref: 'gioi-thieu/',
  },
  products: {
    label: 'SẢN PHẨM',
    title: ['SẢN PHẨM'],
    titleAccentIndex: -1,
    desc: '',
    catalogHref: 'danh-muc-san-pham/',
    bg: {
      src: 'https://images.unsplash.com/photo-1556912173-46c336c7fd55?auto=format&fit=crop&w=3840&q=90',
      overlay: 0.9,
      tone: 'cream',
      pattern: 'cell',
    },
    categories: [
      { id: 'all', label: 'Tất cả' },
      { id: 'panel', label: 'Đèn LED Panel' },
      { id: 'am-tran', label: 'Âm trần' },
      { id: 'nha-xuong', label: 'Nhà xưởng' },
      { id: 'pha', label: 'Đèn pha' },
      { id: 'duong', label: 'Đèn đường' },
      { id: 'nlmt', label: 'Đèn NLMT' },
    ],
    items: [
      {
        slug: 'den-led-panel-48w',
        category: 'panel',
        brand: 'PANEL',
        code: 'LED-PANEL-48',
        name: 'Đèn LED Panel 48W',
        summary: 'Ánh sáng đều, phù hợp văn phòng và trung tâm thương mại.',
        price: 680000,
        compareAt: 790000,
        discount: 14,
        image: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=900&q=85',
        specs: ['Công suất 48W', 'Độ hoàn màu cao', 'BH 3 năm'],
      },
      {
        slug: 'den-led-panel-36w',
        category: 'panel',
        brand: 'PANEL',
        code: 'LED-PANEL-36',
        name: 'Đèn LED Panel 36W',
        price: 520000,
        image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=900&q=85',
      },
      {
        slug: 'den-led-panel-60w',
        category: 'panel',
        brand: 'PANEL',
        code: 'LED-PANEL-60',
        name: 'Đèn LED Panel 60W',
        price: 820000,
        image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=900&q=85',
      },
      {
        slug: 'den-led-panel-72w',
        category: 'panel',
        brand: 'PANEL',
        code: 'LED-PANEL-72',
        name: 'Đèn LED Panel 72W',
        price: 980000,
        image: 'https://images.unsplash.com/photo-1556912173-46c336c7fd55?auto=format&fit=crop&w=900&q=85',
      },
      {
        slug: 'den-led-am-tran-12w',
        category: 'am-tran',
        brand: 'DOWNLIGHT',
        code: 'LED-DL-12',
        name: 'Đèn LED Âm Trần 12W',
        price: 185000,
        image: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=900&q=85',
      },
      {
        slug: 'den-led-am-tran-18w',
        category: 'am-tran',
        brand: 'DOWNLIGHT',
        code: 'LED-DL-18',
        name: 'Đèn LED Âm Trần 18W',
        price: 245000,
        image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=900&q=85',
      },
      {
        slug: 'den-led-am-tran-24w',
        category: 'am-tran',
        brand: 'DOWNLIGHT',
        code: 'LED-DL-24',
        name: 'Đèn LED Âm Trần 24W',
        price: 295000,
        image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=900&q=85',
      },
      {
        slug: 'den-led-nha-xuong-150w',
        category: 'nha-xuong',
        brand: 'HIGHBAY',
        code: 'LED-HB-150',
        name: 'Đèn LED Nhà Xưởng 150W',
        price: 2890000,
        image: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&w=900&q=85',
      },
      {
        slug: 'den-led-nha-xuong-200w',
        category: 'nha-xuong',
        brand: 'HIGHBAY',
        code: 'LED-HB-200',
        name: 'Đèn LED Nhà Xưởng 200W',
        price: 3450000,
        image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=900&q=85',
      },
      {
        slug: 'den-led-nha-xuong-100w',
        category: 'nha-xuong',
        brand: 'HIGHBAY',
        code: 'LED-HB-100',
        name: 'Đèn LED Nhà Xưởng 100W',
        price: 2150000,
        image: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=900&q=85',
      },
      {
        slug: 'den-led-pha-200w',
        category: 'pha',
        brand: 'FLOOD',
        code: 'LED-FL-200',
        name: 'Đèn LED Pha 200W',
        price: 3200000,
        image: 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?auto=format&fit=crop&w=900&q=85',
      },
      {
        slug: 'den-led-pha-150w',
        category: 'pha',
        brand: 'FLOOD',
        code: 'LED-FL-150',
        name: 'Đèn LED Pha 150W',
        price: 2680000,
        image: 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=900&q=85',
      },
      {
        slug: 'den-led-duong-120w',
        category: 'duong',
        brand: 'STREET',
        code: 'LED-ST-120',
        name: 'Đèn LED Đường 120W',
        price: 4650000,
        image: 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?auto=format&fit=crop&w=900&q=85',
      },
      {
        slug: 'den-led-duong-100w',
        category: 'duong',
        brand: 'STREET',
        code: 'LED-ST-100',
        name: 'Đèn LED Đường 100W',
        price: 3980000,
        image: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=900&q=85',
      },
      {
        slug: 'den-led-nang-luong-mat-troi-60w',
        category: 'nlmt',
        brand: 'SOLAR LED',
        code: 'LED-SOL-60',
        name: 'Đèn LED Năng Lượng Mặt Trời 60W',
        price: 1450000,
        image: 'https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?auto=format&fit=crop&w=900&q=85',
      },
      {
        slug: 'den-led-nang-luong-mat-troi-100w',
        category: 'nlmt',
        brand: 'SOLAR LED',
        code: 'LED-SOL-100',
        name: 'Đèn LED Năng Lượng Mặt Trời 100W',
        price: 1980000,
        image: 'https://images.unsplash.com/photo-1497440001374-f26997328c1b?auto=format&fit=crop&w=900&q=85',
      },
    ],
  },
  projects: {
    label: 'DỰ ÁN TIÊU BIỂU',
    title: ['DỰ ÁN ', 'ĐÃ THỰC HIỆN'],
    titleAccentIndex: 1,
    desc: '',
    catalogHref: 'du-an/',
    bg: {
      src: 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=3840&q=90',
      overlay: 0.9,
      tone: 'light',
      pattern: 'energy',
    },
    items: [
      {
        slug: 'nha-xuong-long-an',
        cat: 'NHÀ XƯỞNG',
        title: 'Nhà xưởng Long An',
        summary: 'Hệ thống highbay LED tối ưu độ rọi và tiết kiệm điện.',
        power: '220 highbay',
        place: 'Long An',
        year: '2024',
        area: '12.000m²',
        system: 'Highbay LED',
        image: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&w=1200&q=85',
      },
      {
        slug: 'van-phong-quan-1',
        cat: 'VĂN PHÒNG',
        title: 'Văn phòng Quận 1',
        summary: 'Panel LED hoàn màu cao, không gian làm việc dịu mắt.',
        power: '480 panel',
        place: 'TP.HCM',
        year: '2024',
        area: '2.400m²',
        system: 'Panel LED',
        image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=85',
      },
      {
        slug: 'truong-hoc-binh-duong',
        cat: 'TRƯỜNG HỌC',
        title: 'Trường học Bình Dương',
        summary: 'Ánh sáng chuẩn lớp học, hạn chế chói và tiết kiệm vận hành.',
        power: '360 điểm sáng',
        place: 'Bình Dương',
        year: '2023',
        area: '8.500m²',
        system: 'Panel + Tube',
        image: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?auto=format&fit=crop&w=1200&q=85',
      },
      {
        slug: 'benh-vien-dong-nai',
        cat: 'BỆNH VIỆN',
        title: 'Bệnh viện Đồng Nai',
        summary: 'Ánh sáng ổn định cho khu khám và hành lang nội trú.',
        power: '620 điểm sáng',
        place: 'Đồng Nai',
        year: '2023',
        area: '15.000m²',
        system: 'Medical LED',
        image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=1200&q=85',
      },
      {
        slug: 'khach-san-resort-nha-trang',
        cat: 'KHÁCH SẠN / RESORT',
        title: 'Resort Nha Trang',
        summary: 'Ánh sáng trang trí và chức năng cho sảnh, hành lang, sân vườn.',
        power: '850 điểm sáng',
        place: 'Nha Trang',
        year: '2024',
        area: 'Resort 5*',
        system: 'Decorative LED',
        image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=85',
      },
    ],
  },
  services: {
    label: 'DỊCH VỤ',
    title: ['DỊCH VỤ HỆ THỐNG ', 'ĐÈN LED'],
    titleAccentIndex: 1,
    desc: 'ĐỒNG HÀNH CÙNG BẠN TỪ KHÂU TƯ VẤN ĐẾN BẢO TRÌ HỆ THỐNG',
    catalogHref: 'dich-vu/',
    bg: {
      src: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&w=3840&q=90',
      overlay: 0.78,
      tone: 'mist-white',
      pattern: 'blueprint',
    },
    steps: [
      {
        slug: 'tu-van-chieu-sang',
        num: '01',
        title: 'Tư vấn chiếu sáng',
        text: 'Phân tích nhu cầu không gian, mức độ rọi và ngân sách để đề xuất giải pháp phù hợp.',
        icon: 'search',
        image: 'https://images.unsplash.com/photo-1556745753-b2904692b3cd?auto=format&fit=crop&w=1200&q=85',
      },
      {
        slug: 'thiet-ke-he-thong-den',
        num: '02',
        title: 'Thiết kế hệ thống đèn',
        text: 'Bố trí điểm sáng, chọn công suất và mô phỏng hiệu quả chiếu sáng trước thi công.',
        icon: 'design',
        image: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1200&q=85',
      },
      {
        slug: 'thi-cong-lap-dat',
        num: '03',
        title: 'Thi công lắp đặt',
        text: 'Lắp đặt đúng tiêu chuẩn kỹ thuật, an toàn điện và đúng tiến độ bàn giao.',
        icon: 'build',
        image: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?auto=format&fit=crop&w=1200&q=85',
      },
      {
        slug: 'bao-tri-he-thong',
        num: '04',
        title: 'Bảo trì hệ thống',
        text: 'Kiểm tra, vệ sinh và thay thế linh kiện theo lịch để duy trì hiệu suất.',
        icon: 'maintain',
        image: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=1200&q=85',
      },
      {
        slug: 'nang-cap-den-led',
        num: '05',
        title: 'Nâng cấp đèn LED',
        text: 'Thay thế hệ thống cũ bằng LED hiệu suất cao, giảm chi phí điện ngay.',
        icon: 'bulb',
        image: 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?auto=format&fit=crop&w=1200&q=85',
      },
      {
        slug: 'tiet-kiem-dien',
        num: '06',
        title: 'Tiết kiệm điện',
        text: 'Tối ưu vận hành, cảm biến và lịch chiếu sáng để giảm hóa đơn điện.',
        icon: 'save',
        image: 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=1200&q=85',
      },
    ],
    ctaTitle: 'Bạn cần nâng cấp hệ thống chiếu sáng LED?',
    ctaDesc: 'Đội ngũ kỹ thuật sẵn sàng khảo sát miễn phí và tư vấn giải pháp tối ưu chi phí cho công trình của bạn.',
    ctaBtn: 'NHẬN BÁO GIÁ MIỄN PHÍ',
  },
  testimonials: {
    titleBefore: 'KHÁCH HÀNG ',
    titleAccent: 'NÓI GÌ',
    titleAfter: ' VỀ CHÚNG TÔI',
    bg: {
      src: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=3840&q=90',
      overlay: 0.88,
      tone: 'mist-white',
      pattern: 'blueprint',
    },
    items: [
      {
        image: 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=900&q=85',
        quote: 'Hệ thống LED nhà xưởng sáng đều, tiết kiệm điện rõ rệt. Thi công đúng tiến độ, đội ngũ hỗ trợ tận tâm.',
        name: 'Anh Minh Tuấn',
        role: 'Giám đốc - Công ty TNHH Minh Tuấn',
        avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=200&q=80',
        rating: 5,
      },
      {
        image: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=900&q=85',
        quote: 'Từ tư vấn đến lắp đặt đều chuyên nghiệp. Không gian văn phòng sáng đẹp, nhân viên làm việc dễ chịu hơn.',
        name: 'Anh Quốc Bảo',
        role: 'Giám đốc - Công ty CP Quốc Bảo',
        avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80',
        rating: 5,
      },
      {
        image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=900&q=85',
        quote: 'Đèn đường LED chất lượng tốt, ánh sáng ổn định. Chúng tôi hài lòng và sẽ tiếp tục đồng hành lâu dài.',
        name: 'Anh Hoàng Nam',
        role: 'Quản lý vận hành - Nhà máy Hoàng Nam',
        avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=200&q=80',
        rating: 5,
      },
      {
        image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=900&q=85',
        quote: 'Chiếu sáng khách sạn đẹp, tiết kiệm điện. Báo giá minh bạch, bảo hành rõ ràng.',
        name: 'Chị Thu Hà',
        role: 'Quản lý - Resort Nha Trang',
        avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
        rating: 5,
      },
      {
        image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=900&q=85',
        quote: 'Đội ngũ kỹ thuật chuyên nghiệp, bảo trì chu đáo. Rất yên tâm khi gửi gắm hệ thống chiếu sáng.',
        name: 'Anh Đức Anh',
        role: 'Giám đốc kỹ thuật - KCN Bà Rịa',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
        rating: 5,
      },
    ],
  },
  news: {
    label: 'TIN TỨC',
    title: ['TIN ', 'TỨC'],
    titleAccentIndex: 1,
    desc: 'Cập nhật xu hướng, kiến thức và giải pháp chiếu sáng mới nhất',
    catalogHref: 'tin-tuc/',
    bg: {
      src: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=3840&q=90',
      overlay: 0.86,
      tone: 'mist-white',
      pattern: 'blueprint',
    },
    items: [
      {
        slug: 'kien-thuc-den-led',
        cat: 'NỔI BẬT',
        featured: true,
        date: '30/06/2024',
        datetime: '2024-06-30',
        title: '5 lợi ích khi doanh nghiệp nâng cấp hệ thống chiếu sáng LED',
        excerpt: 'Khám phá những lợi ích vượt trội giúp doanh nghiệp tối ưu chi phí và nâng cao chất lượng không gian.',
        image: 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=1600&q=85',
        content: [
          'Đèn LED khác bóng truyền thống ở hiệu suất quang thông trên mỗi watt và tuổi thọ dài hơn rõ rệt.',
          'Chỉ số CRI cao giúp màu sắc vật thể trung thực hơn — quan trọng với văn phòng, showroom và khách sạn.',
          'Chọn đúng công suất và góc chiếu giúp tránh lãng phí điện và giảm chói.',
        ],
      },
      {
        slug: 'so-sanh-den-led',
        cat: 'HƯỚNG DẪN',
        date: '28/06/2024',
        datetime: '2024-06-28',
        title: 'Hướng dẫn bảo trì hệ thống chiếu sáng LED hiệu quả',
        excerpt: 'Khi nào nên dùng từng dòng đèn để đạt hiệu quả chiếu sáng tối ưu.',
        image: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=85',
        content: [
          'Panel phù hợp trần thạch cao văn phòng; âm trần cho nhà ở và khách sạn; highbay cho nhà xưởng cao.',
          'Mỗi dòng có mức IP, góc chiếu và quang thông khác nhau — không nên dùng chung một loại cho mọi không gian.',
        ],
      },
      {
        slug: 'tiet-kiem-dien-voi-led',
        cat: 'TIN TỨC',
        date: '25/06/2024',
        datetime: '2024-06-25',
        title: 'Xu hướng chiếu sáng thông minh trong năm 2024',
        excerpt: 'Số liệu tham khảo khi thay hệ thống chiếu sáng cũ bằng LED công nghiệp.',
        image: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1200&q=85',
        content: [
          'Nhiều nhà xưởng giảm 40–60% chi phí chiếu sáng sau khi chuyển sang LED highbay.',
          'Kết hợp cảm biến chuyển động và lịch tắt sáng giúp tăng thêm mức tiết kiệm.',
        ],
      },
      {
        slug: 'thiet-ke-anh-sang',
        cat: 'KIẾN THỨC',
        date: '20/06/2024',
        datetime: '2024-06-20',
        title: 'Chi phí lắp đặt hệ thống LED mới nhất 2024',
        excerpt: 'Nguyên tắc lớp sáng (ambient, task, accent) cho nội thất hiện đại.',
        image: 'https://images.unsplash.com/photo-1556912173-46c336c7fd55?auto=format&fit=crop&w=1200&q=85',
        content: [
          'Thiết kế ánh sáng tốt giúp không gian vừa đủ sáng làm việc vừa tạo cảm xúc thương hiệu.',
          'Nên mô phỏng độ rọi trước khi thi công để tránh phải chỉnh sửa tốn kém.',
        ],
      },
      {
        slug: 'chieu-sang-nha-xuong',
        cat: 'NHÀ XƯỞNG',
        date: '15/06/2026',
        datetime: '2026-06-15',
        title: 'Chiếu sáng nhà xưởng: độ rọi, chống chói và an toàn',
        excerpt: 'Các lưu ý về chiều cao treo đèn, khoảng cách điểm sáng và tiêu chuẩn an toàn.',
        image: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&w=1200&q=85',
        content: [
          'Độ rọi khuyến nghị phụ thuộc loại hình sản xuất — lắp ráp tinh xảo cần mức sáng cao hơn kho bãi.',
          'Chống chói và phân bố đều giúp giảm mệt mắt, tăng năng suất lao động.',
        ],
      },
      {
        slug: 'chieu-sang-dan-dung',
        cat: 'DÂN DỤNG',
        date: '02/06/2026',
        datetime: '2026-06-02',
        title: 'Chiếu sáng dân dụng: chọn nhiệt độ màu phù hợp',
        excerpt: 'Warm white, neutral và cool white — dùng đúng không gian trong nhà.',
        image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=85',
        content: [
          'Phòng khách và phòng ngủ thường dùng ánh sáng ấm; bàn làm việc và bếp nên dùng trung tính.',
          'Kết hợp dimmer giúp linh hoạt theo thời điểm trong ngày.',
        ],
      },
    ],
  },
  contact: {
    label: 'LIÊN HỆ',
    title: ['SẴN SÀNG ĐỒNG HÀNH', 'CÙNG DỰ ÁN CỦA BẠN'],
    desc: 'Để lại thông tin để được khảo sát miễn phí và tư vấn giải pháp đèn LED tối ưu chi phí vận hành.',
    bg: 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=3840&q=90',
    phone: '0938 961 012',
    phoneTel: '0938961012',
    email: 'led@solarmiennam.vn',
    address: 'Số 12 Nguyễn Văn Linh, Quận 7, TP. Hồ Chí Minh',
    website: 'www.solarmiennam.vn',
    zalo: 'https://zalo.me/0938961012',
    hours: 'Thứ 2 – Thứ 7: 8:00 – 17:30',
    benefits: [
      'Khảo sát miễn phí',
      'Báo giá nhanh trong 24 giờ',
      'Tư vấn giải pháp tối ưu',
      'Bảo hành chính hãng',
    ],
    socials: {
      facebook: 'https://facebook.com',
      zalo: 'https://zalo.me/0938961012',
      youtube: 'https://youtube.com',
    },
    form: {
      title: 'ĐĂNG KÝ NHẬN TƯ VẤN',
      projectTypes: ['Nhà xưởng', 'Văn phòng', 'Khách sạn', 'Đường phố', 'Dân dụng', 'Khác'],
      needs: ['Đèn nhà xưởng', 'Đèn đường', 'Đèn pha', 'Panel / âm trần', 'Nâng cấp LED', 'Khảo sát'],
      consent: 'Tôi đồng ý để Solar Miền Nam liên hệ tư vấn.',
      submit: 'GỬI YÊU CẦU TƯ VẤN',
      successTitle: 'Cảm ơn Quý khách.',
      successDesc: 'Solar Miền Nam sẽ liên hệ trong thời gian sớm nhất.',
    },
  },
  footer: {
    about:
      'Solar Miền Nam cung cấp giải pháp chiếu sáng LED chuyên biệt cho nhà xưởng, khu công nghiệp, đường phố, khách sạn, trường học và trung tâm thương mại.',
    productLinks: [
      { label: 'Đèn LED Panel', href: 'san-pham/den-led-panel-48w/' },
      { label: 'Đèn LED Âm Trần', href: 'san-pham/den-led-am-tran-12w/' },
      { label: 'Đèn LED Nhà Xưởng', href: 'san-pham/den-led-nha-xuong-150w/' },
      { label: 'Đèn LED Pha', href: 'san-pham/den-led-pha-200w/' },
      { label: 'Đèn LED Đường', href: 'san-pham/den-led-duong-120w/' },
      { label: 'Đèn LED NLMT', href: 'san-pham/den-led-nang-luong-mat-troi-60w/' },
    ],
    serviceLinks: [
      { label: 'Tư vấn chiếu sáng', href: 'dich-vu/tu-van-chieu-sang/' },
      { label: 'Thiết kế hệ thống đèn', href: 'dich-vu/thiet-ke-he-thong-den/' },
      { label: 'Thi công lắp đặt', href: 'dich-vu/thi-cong-lap-dat/' },
      { label: 'Bảo trì hệ thống', href: 'dich-vu/bao-tri-he-thong/' },
      { label: 'Tin tức', href: 'tin-tuc/' },
    ],
  },
};
