/**
 * Shared theme: Solar — Điện mặt trời
 */
window.SiteThemes = window.SiteThemes || {};
window.SiteThemes.solar = {
  id: 'solar',
  colors: {
    primary: '#F97316',
    primaryHover: '#ea6a0c',
    secondary: '#111827',
    accent: '#F97316',
  },
  meta: {
    title: 'Solar Miền Nam | Giải pháp điện mặt trời toàn diện',
    description: 'Solar Miền Nam — Giải pháp điện mặt trời toàn diện cho gia đình, doanh nghiệp và nhà xưởng.',
  },
  industryTitle: 'ĐIỆN MẶT TRỜI',
  brand: { name: 'Solar', sub: 'Miền Nam' },
  hero: {
    slides: [
      { src: '../assets/backgrounds/bg-section-01-hero.png', alt: 'Cánh đồng điện mặt trời buổi sáng sớm' },
      { src: '../assets/backgrounds/bg-section-04-projects.png', alt: 'Trang trại điện mặt trời quy mô lớn lúc hoàng hôn' },
      { src: '../assets/backgrounds/bg-section-07-contact.png', alt: 'Mái nhà lắp pin mặt trời lúc hoàng hôn' },
      { src: '../assets/backgrounds/bg-section-03-products.png', alt: 'Tấm pin năng lượng mặt trời góc chụp chuyên nghiệp' },
    ],
    title: ['GIẢI PHÁP', 'ĐIỆN NĂNG LƯỢNG', 'MẶT TRỜI'],
    titleAccentIndex: 1,
    desc: 'Giải pháp tiết kiệm điện và phát triển bền vững dành cho hộ gia đình, doanh nghiệp và nhà xưởng.',
    ctaPrimary: 'Liên hệ Zalo',
    ctaSecondary: 'Xem sản phẩm',
    ctaSecondaryHref: 'san-pham/',
  },
  about: {
    label: 'VỀ CHÚNG TÔI',
    titleLines: ['NĂNG LƯỢNG SẠCH CHO TƯƠNG LAI ', 'BỀN VỮNG'],
    titleAccentIndex: 1,
    desc: 'Với hơn 10 năm kinh nghiệm trong lĩnh vực năng lượng tái tạo, Solar Miền Nam mang đến các giải pháp điện mặt trời hiệu quả, an toàn và tối ưu nhất cho doanh nghiệp và hộ gia đình.',
    highlight: 'Chúng tôi cam kết đồng hành cùng khách hàng trên hành trình chuyển đổi năng lượng xanh, tiết kiệm chi phí và bảo vệ môi trường.',
    image: '../assets/backgrounds/bg-about-media.png',
    imageAlt: 'Tòa nhà hiện đại với hệ thống pin năng lượng mặt trời trên mái',
    bg: {
      src: '../assets/backgrounds/bg-about-media.png',
      overlay: 0.96,
      tone: 'sky',
      pattern: 'dots-circuit',
    },
    features: [],
    cta: 'XEM THÊM',
    ctaHref: 'gioi-thieu/',
  },
  products: {
    label: 'SẢN PHẨM',
    title: ['SẢN PHẨM'],
    titleAccentIndex: -1,
    desc: '',
    catalogHref: 'san-pham/',
    bg: {
      src: '../assets/backgrounds/bg-products-hero.png',
      overlay: 0.62,
      tone: 'sky',
      pattern: 'none',
    },
    categories: [
      { id: 'den-nlmt', label: 'Đèn năng lượng mặt trời' },
      { id: 'pin-luu-tru', label: 'Pin lưu trữ' },
      { id: 'inverter', label: 'Inverter' },
      { id: 'tam-pin', label: 'Tấm pin năng lượng' },
      { id: 'phu-kien', label: 'Phụ kiện' },
      { id: 'thiet-bi-dien', label: 'Thiết bị điện' },
    ],
    items: [
      {
        slug: 'den-duong-jd-9900-200w',
        category: 'den-nlmt',
        brand: 'JD',
        code: 'JD-9900',
        name: 'Đèn đường năng lượng JD-9900 200W',
        price: 1890000,
        image: '../assets/products/den-01.png',
        specs: ['200W', 'Pin tích hợp', 'BH 2 năm'],
      },
      {
        slug: 'den-pha-nlmt-300w',
        category: 'den-nlmt',
        brand: 'SOLAR',
        code: 'FL-300',
        name: 'Đèn pha năng lượng mặt trời 300W',
        price: 2450000,
        image: '../assets/products/den-02.png',
        specs: ['300W', 'IP65', 'BH 2 năm'],
      },
      {
        slug: 'den-san-vuon-60w',
        category: 'den-nlmt',
        brand: 'GARDEN',
        code: 'GV-60',
        name: 'Đèn sân vườn năng lượng 60W',
        price: 890000,
        image: '../assets/products/den-03.png',
        specs: ['60W', 'Cảm biến sáng', 'BH 2 năm'],
      },
      {
        slug: 'den-cong-120w',
        category: 'den-nlmt',
        brand: 'GATE',
        code: 'GT-120',
        name: 'Đèn cổng năng lượng mặt trời 120W',
        price: 1350000,
        image: '../assets/products/den-04.png',
        specs: ['120W', 'Remote', 'BH 2 năm'],
      },
      {
        slug: 'den-duong-jd-8800-150w',
        category: 'den-nlmt',
        brand: 'JD',
        code: 'JD-8800',
        name: 'Đèn đường năng lượng JD-8800 150W',
        price: 1650000,
        image: '../assets/products/den-05.png',
        specs: ['150W', 'Pin LiFePO4', 'BH 2 năm'],
      },
      {
        slug: 'den-pha-nlmt-200w',
        category: 'den-nlmt',
        brand: 'SOLAR',
        code: 'FL-200',
        name: 'Đèn pha năng lượng mặt trời 200W',
        price: 1980000,
        image: '../assets/products/den-06.png',
        specs: ['200W', 'IP66', 'BH 2 năm'],
      },
      {
        slug: 'den-ban-cong-40w',
        category: 'den-nlmt',
        brand: 'BALCONY',
        code: 'BC-40',
        name: 'Đèn ban công năng lượng 40W',
        price: 650000,
        image: '../assets/products/den-07.png',
        specs: ['40W', 'Chống nước', 'BH 2 năm'],
      },
      {
        slug: 'den-cam-bien-80w',
        category: 'den-nlmt',
        brand: 'SENSOR',
        code: 'SN-80',
        name: 'Đèn cảm biến năng lượng 80W',
        price: 1120000,
        image: '../assets/products/den-08.png',
        specs: ['80W', 'PIR', 'BH 2 năm'],
      },
      {
        slug: 'den-duong-jd-7700-100w',
        category: 'den-nlmt',
        brand: 'JD',
        code: 'JD-7700',
        name: 'Đèn đường năng lượng JD-7700 100W',
        price: 1290000,
        image: '../assets/products/den-01.png',
      },
      {
        slug: 'den-pha-nlmt-100w',
        category: 'den-nlmt',
        brand: 'SOLAR',
        code: 'FL-100',
        name: 'Đèn pha năng lượng mặt trời 100W',
        price: 980000,
        image: '../assets/products/den-02.png',
      },
      {
        slug: 'den-tru-san-90w',
        category: 'den-nlmt',
        brand: 'POLE',
        code: 'PL-90',
        name: 'Đèn trụ sân năng lượng 90W',
        price: 1560000,
        image: '../assets/products/den-03.png',
      },
      {
        slug: 'den-tuong-nlmt-50w',
        category: 'den-nlmt',
        brand: 'WALL',
        code: 'WL-50',
        name: 'Đèn tường năng lượng mặt trời 50W',
        price: 720000,
        image: '../assets/products/den-04.png',
      },
      {
        slug: 'den-duong-jd-6600-80w',
        category: 'den-nlmt',
        brand: 'JD',
        code: 'JD-6600',
        name: 'Đèn đường năng lượng JD-6600 80W',
        price: 1050000,
        image: '../assets/products/den-05.png',
      },
      {
        slug: 'den-pha-nlmt-150w',
        category: 'den-nlmt',
        brand: 'SOLAR',
        code: 'FL-150',
        name: 'Đèn pha năng lượng mặt trời 150W',
        price: 1680000,
        image: '../assets/products/den-06.png',
      },
      {
        slug: 'den-san-bong-70w',
        category: 'den-nlmt',
        brand: 'SPORT',
        code: 'SP-70',
        name: 'Đèn sân bóng năng lượng 70W',
        price: 1420000,
        image: '../assets/products/den-07.png',
      },
      {
        slug: 'den-cong-park-110w',
        category: 'den-nlmt',
        brand: 'PARK',
        code: 'PK-110',
        name: 'Đèn công viên năng lượng 110W',
        price: 1750000,
        image: '../assets/products/den-08.png',
      },
      {
        slug: 'den-duong-jd-9900-200w-p17',
        category: 'den-nlmt',
        brand: 'JD',
        code: 'JD-9900',
        name: 'Đèn đường năng lượng JD-9900 200W',
        price: 1890000,
        image: '../assets/products/den-01.png',
        specs: ['200W', 'Pin tích hợp', 'BH 2 năm'],
      },
      {
        slug: 'den-pha-nlmt-300w-p18',
        category: 'den-nlmt',
        brand: 'SOLAR',
        code: 'FL-300',
        name: 'Đèn pha năng lượng mặt trời 300W',
        price: 2450000,
        image: '../assets/products/den-02.png',
        specs: ['300W', 'IP65', 'BH 2 năm'],
      },
      {
        slug: 'den-san-vuon-60w-p19',
        category: 'den-nlmt',
        brand: 'GARDEN',
        code: 'GV-60',
        name: 'Đèn sân vườn năng lượng 60W',
        price: 890000,
        image: '../assets/products/den-03.png',
        specs: ['60W', 'Cảm biến sáng', 'BH 2 năm'],
      },
      {
        slug: 'den-cong-120w-p20',
        category: 'den-nlmt',
        brand: 'GATE',
        code: 'GT-120',
        name: 'Đèn cổng năng lượng mặt trời 120W',
        price: 1350000,
        image: '../assets/products/den-04.png',
        specs: ['120W', 'Remote', 'BH 2 năm'],
      },
      {
        slug: 'den-duong-jd-8800-150w-p21',
        category: 'den-nlmt',
        brand: 'JD',
        code: 'JD-8800',
        name: 'Đèn đường năng lượng JD-8800 150W',
        price: 1650000,
        image: '../assets/products/den-05.png',
        specs: ['150W', 'Pin LiFePO4', 'BH 2 năm'],
      },
      {
        slug: 'den-pha-nlmt-200w-p22',
        category: 'den-nlmt',
        brand: 'SOLAR',
        code: 'FL-200',
        name: 'Đèn pha năng lượng mặt trời 200W',
        price: 1980000,
        image: '../assets/products/den-06.png',
        specs: ['200W', 'IP66', 'BH 2 năm'],
      },
      {
        slug: 'den-ban-cong-40w-p23',
        category: 'den-nlmt',
        brand: 'BALCONY',
        code: 'BC-40',
        name: 'Đèn ban công năng lượng 40W',
        price: 650000,
        image: '../assets/products/den-07.png',
        specs: ['40W', 'Chống nước', 'BH 2 năm'],
      },
      {
        slug: 'den-cam-bien-80w-p24',
        category: 'den-nlmt',
        brand: 'SENSOR',
        code: 'SN-80',
        name: 'Đèn cảm biến năng lượng 80W',
        price: 1120000,
        image: '../assets/products/den-08.png',
        specs: ['80W', 'PIR', 'BH 2 năm'],
      },
      {
        slug: 'den-duong-jd-7700-100w-p25',
        category: 'den-nlmt',
        brand: 'JD',
        code: 'JD-7700',
        name: 'Đèn đường năng lượng JD-7700 100W',
        price: 1290000,
        image: '../assets/products/den-01.png',
      },
      {
        slug: 'den-pha-nlmt-100w-p26',
        category: 'den-nlmt',
        brand: 'SOLAR',
        code: 'FL-100',
        name: 'Đèn pha năng lượng mặt trời 100W',
        price: 980000,
        image: '../assets/products/den-02.png',
      },
      {
        slug: 'den-tru-san-90w-p27',
        category: 'den-nlmt',
        brand: 'POLE',
        code: 'PL-90',
        name: 'Đèn trụ sân năng lượng 90W',
        price: 1560000,
        image: '../assets/products/den-03.png',
      },
      {
        slug: 'den-tuong-nlmt-50w-p28',
        category: 'den-nlmt',
        brand: 'WALL',
        code: 'WL-50',
        name: 'Đèn tường năng lượng mặt trời 50W',
        price: 720000,
        image: '../assets/products/den-04.png',
      },
      {
        slug: 'den-duong-jd-6600-80w-p29',
        category: 'den-nlmt',
        brand: 'JD',
        code: 'JD-6600',
        name: 'Đèn đường năng lượng JD-6600 80W',
        price: 1050000,
        image: '../assets/products/den-05.png',
      },
      {
        slug: 'den-pha-nlmt-150w-p30',
        category: 'den-nlmt',
        brand: 'SOLAR',
        code: 'FL-150',
        name: 'Đèn pha năng lượng mặt trời 150W',
        price: 1680000,
        image: '../assets/products/den-06.png',
      },
      {
        slug: 'den-san-bong-70w-p31',
        category: 'den-nlmt',
        brand: 'SPORT',
        code: 'SP-70',
        name: 'Đèn sân bóng năng lượng 70W',
        price: 1420000,
        image: '../assets/products/den-07.png',
      },
      {
        slug: 'den-cong-park-110w-p32',
        category: 'den-nlmt',
        brand: 'PARK',
        code: 'PK-110',
        name: 'Đèn công viên năng lượng 110W',
        price: 1750000,
        image: '../assets/products/den-08.png',
      },
      {
        slug: 'den-duong-jd-9900-200w-p33',
        category: 'den-nlmt',
        brand: 'JD',
        code: 'JD-9900',
        name: 'Đèn đường năng lượng JD-9900 200W',
        price: 1890000,
        image: '../assets/products/den-01.png',
        specs: ['200W', 'Pin tích hợp', 'BH 2 năm'],
      },
      {
        slug: 'den-pha-nlmt-300w-p34',
        category: 'den-nlmt',
        brand: 'SOLAR',
        code: 'FL-300',
        name: 'Đèn pha năng lượng mặt trời 300W',
        price: 2450000,
        image: '../assets/products/den-02.png',
        specs: ['300W', 'IP65', 'BH 2 năm'],
      },
      {
        slug: 'den-san-vuon-60w-p35',
        category: 'den-nlmt',
        brand: 'GARDEN',
        code: 'GV-60',
        name: 'Đèn sân vườn năng lượng 60W',
        price: 890000,
        image: '../assets/products/den-03.png',
        specs: ['60W', 'Cảm biến sáng', 'BH 2 năm'],
      },
      {
        slug: 'den-cong-120w-p36',
        category: 'den-nlmt',
        brand: 'GATE',
        code: 'GT-120',
        name: 'Đèn cổng năng lượng mặt trời 120W',
        price: 1350000,
        image: '../assets/products/den-04.png',
        specs: ['120W', 'Remote', 'BH 2 năm'],
      },
      {
        slug: 'den-duong-jd-8800-150w-p37',
        category: 'den-nlmt',
        brand: 'JD',
        code: 'JD-8800',
        name: 'Đèn đường năng lượng JD-8800 150W',
        price: 1650000,
        image: '../assets/products/den-05.png',
        specs: ['150W', 'Pin LiFePO4', 'BH 2 năm'],
      },
      {
        slug: 'den-pha-nlmt-200w-p38',
        category: 'den-nlmt',
        brand: 'SOLAR',
        code: 'FL-200',
        name: 'Đèn pha năng lượng mặt trời 200W',
        price: 1980000,
        image: '../assets/products/den-06.png',
        specs: ['200W', 'IP66', 'BH 2 năm'],
      },
      {
        slug: 'den-ban-cong-40w-p39',
        category: 'den-nlmt',
        brand: 'BALCONY',
        code: 'BC-40',
        name: 'Đèn ban công năng lượng 40W',
        price: 650000,
        image: '../assets/products/den-07.png',
        specs: ['40W', 'Chống nước', 'BH 2 năm'],
      },
      {
        slug: 'den-cam-bien-80w-p40',
        category: 'den-nlmt',
        brand: 'SENSOR',
        code: 'SN-80',
        name: 'Đèn cảm biến năng lượng 80W',
        price: 1120000,
        image: '../assets/products/den-08.png',
        specs: ['80W', 'PIR', 'BH 2 năm'],
      },
      {
        slug: 'den-duong-jd-7700-100w-p41',
        category: 'den-nlmt',
        brand: 'JD',
        code: 'JD-7700',
        name: 'Đèn đường năng lượng JD-7700 100W',
        price: 1290000,
        image: '../assets/products/den-01.png',
      },
      {
        slug: 'den-pha-nlmt-100w-p42',
        category: 'den-nlmt',
        brand: 'SOLAR',
        code: 'FL-100',
        name: 'Đèn pha năng lượng mặt trời 100W',
        price: 980000,
        image: '../assets/products/den-02.png',
      },
      {
        slug: 'den-tru-san-90w-p43',
        category: 'den-nlmt',
        brand: 'POLE',
        code: 'PL-90',
        name: 'Đèn trụ sân năng lượng 90W',
        price: 1560000,
        image: '../assets/products/den-03.png',
      },
      {
        slug: 'den-tuong-nlmt-50w-p44',
        category: 'den-nlmt',
        brand: 'WALL',
        code: 'WL-50',
        name: 'Đèn tường năng lượng mặt trời 50W',
        price: 720000,
        image: '../assets/products/den-04.png',
      },
      {
        slug: 'den-duong-jd-6600-80w-p45',
        category: 'den-nlmt',
        brand: 'JD',
        code: 'JD-6600',
        name: 'Đèn đường năng lượng JD-6600 80W',
        price: 1050000,
        image: '../assets/products/den-05.png',
      },
      {
        slug: 'den-pha-nlmt-150w-p46',
        category: 'den-nlmt',
        brand: 'SOLAR',
        code: 'FL-150',
        name: 'Đèn pha năng lượng mặt trời 150W',
        price: 1680000,
        image: '../assets/products/den-06.png',
      },
      {
        slug: 'den-san-bong-70w-p47',
        category: 'den-nlmt',
        brand: 'SPORT',
        code: 'SP-70',
        name: 'Đèn sân bóng năng lượng 70W',
        price: 1420000,
        image: '../assets/products/den-07.png',
      },
      {
        slug: 'den-cong-park-110w-p48',
        category: 'den-nlmt',
        brand: 'PARK',
        code: 'PK-110',
        name: 'Đèn công viên năng lượng 110W',
        price: 1750000,
        image: '../assets/products/den-08.png',
      },
      {
        slug: 'den-duong-jd-9900-200w-p49',
        category: 'den-nlmt',
        brand: 'JD',
        code: 'JD-9900',
        name: 'Đèn đường năng lượng JD-9900 200W',
        price: 1890000,
        image: '../assets/products/den-01.png',
        specs: ['200W', 'Pin tích hợp', 'BH 2 năm'],
      },
      {
        slug: 'den-pha-nlmt-300w-p50',
        category: 'den-nlmt',
        brand: 'SOLAR',
        code: 'FL-300',
        name: 'Đèn pha năng lượng mặt trời 300W',
        price: 2450000,
        image: '../assets/products/den-02.png',
        specs: ['300W', 'IP65', 'BH 2 năm'],
      },
      {
        slug: 'den-san-vuon-60w-p51',
        category: 'den-nlmt',
        brand: 'GARDEN',
        code: 'GV-60',
        name: 'Đèn sân vườn năng lượng 60W',
        price: 890000,
        image: '../assets/products/den-03.png',
        specs: ['60W', 'Cảm biến sáng', 'BH 2 năm'],
      },
      {
        slug: 'den-cong-120w-p52',
        category: 'den-nlmt',
        brand: 'GATE',
        code: 'GT-120',
        name: 'Đèn cổng năng lượng mặt trời 120W',
        price: 1350000,
        image: '../assets/products/den-04.png',
        specs: ['120W', 'Remote', 'BH 2 năm'],
      },
      {
        slug: 'den-duong-jd-8800-150w-p53',
        category: 'den-nlmt',
        brand: 'JD',
        code: 'JD-8800',
        name: 'Đèn đường năng lượng JD-8800 150W',
        price: 1650000,
        image: '../assets/products/den-05.png',
        specs: ['150W', 'Pin LiFePO4', 'BH 2 năm'],
      },
      {
        slug: 'den-pha-nlmt-200w-p54',
        category: 'den-nlmt',
        brand: 'SOLAR',
        code: 'FL-200',
        name: 'Đèn pha năng lượng mặt trời 200W',
        price: 1980000,
        image: '../assets/products/den-06.png',
        specs: ['200W', 'IP66', 'BH 2 năm'],
      },
      {
        slug: 'den-ban-cong-40w-p55',
        category: 'den-nlmt',
        brand: 'BALCONY',
        code: 'BC-40',
        name: 'Đèn ban công năng lượng 40W',
        price: 650000,
        image: '../assets/products/den-07.png',
        specs: ['40W', 'Chống nước', 'BH 2 năm'],
      },
      {
        slug: 'den-cam-bien-80w-p56',
        category: 'den-nlmt',
        brand: 'SENSOR',
        code: 'SN-80',
        name: 'Đèn cảm biến năng lượng 80W',
        price: 1120000,
        image: '../assets/products/den-08.png',
        specs: ['80W', 'PIR', 'BH 2 năm'],
      },
      {
        slug: 'den-duong-jd-7700-100w-p57',
        category: 'den-nlmt',
        brand: 'JD',
        code: 'JD-7700',
        name: 'Đèn đường năng lượng JD-7700 100W',
        price: 1290000,
        image: '../assets/products/den-01.png',
      },
      {
        slug: 'den-pha-nlmt-100w-p58',
        category: 'den-nlmt',
        brand: 'SOLAR',
        code: 'FL-100',
        name: 'Đèn pha năng lượng mặt trời 100W',
        price: 980000,
        image: '../assets/products/den-02.png',
      },
      {
        slug: 'den-tru-san-90w-p59',
        category: 'den-nlmt',
        brand: 'POLE',
        code: 'PL-90',
        name: 'Đèn trụ sân năng lượng 90W',
        price: 1560000,
        image: '../assets/products/den-03.png',
      },
      {
        slug: 'den-tuong-nlmt-50w-p60',
        category: 'den-nlmt',
        brand: 'WALL',
        code: 'WL-50',
        name: 'Đèn tường năng lượng mặt trời 50W',
        price: 720000,
        image: '../assets/products/den-04.png',
      },
      {
        slug: 'den-duong-jd-6600-80w-p61',
        category: 'den-nlmt',
        brand: 'JD',
        code: 'JD-6600',
        name: 'Đèn đường năng lượng JD-6600 80W',
        price: 1050000,
        image: '../assets/products/den-05.png',
      },
      {
        slug: 'den-pha-nlmt-150w-p62',
        category: 'den-nlmt',
        brand: 'SOLAR',
        code: 'FL-150',
        name: 'Đèn pha năng lượng mặt trời 150W',
        price: 1680000,
        image: '../assets/products/den-06.png',
      },
      {
        slug: 'den-san-bong-70w-p63',
        category: 'den-nlmt',
        brand: 'SPORT',
        code: 'SP-70',
        name: 'Đèn sân bóng năng lượng 70W',
        price: 1420000,
        image: '../assets/products/den-07.png',
      },
      {
        slug: 'den-cong-park-110w-p64',
        category: 'den-nlmt',
        brand: 'PARK',
        code: 'PK-110',
        name: 'Đèn công viên năng lượng 110W',
        price: 1750000,
        image: '../assets/products/den-08.png',
      },
      {
        slug: 'den-duong-jd-9900-200w-p65',
        category: 'den-nlmt',
        brand: 'JD',
        code: 'JD-9900',
        name: 'Đèn đường năng lượng JD-9900 200W',
        price: 1890000,
        image: '../assets/products/den-01.png',
        specs: ['200W', 'Pin tích hợp', 'BH 2 năm'],
      },
      {
        slug: 'den-pha-nlmt-300w-p66',
        category: 'den-nlmt',
        brand: 'SOLAR',
        code: 'FL-300',
        name: 'Đèn pha năng lượng mặt trời 300W',
        price: 2450000,
        image: '../assets/products/den-02.png',
        specs: ['300W', 'IP65', 'BH 2 năm'],
      },
      {
        slug: 'den-san-vuon-60w-p67',
        category: 'den-nlmt',
        brand: 'GARDEN',
        code: 'GV-60',
        name: 'Đèn sân vườn năng lượng 60W',
        price: 890000,
        image: '../assets/products/den-03.png',
        specs: ['60W', 'Cảm biến sáng', 'BH 2 năm'],
      },
      {
        slug: 'den-cong-120w-p68',
        category: 'den-nlmt',
        brand: 'GATE',
        code: 'GT-120',
        name: 'Đèn cổng năng lượng mặt trời 120W',
        price: 1350000,
        image: '../assets/products/den-04.png',
        specs: ['120W', 'Remote', 'BH 2 năm'],
      },
      {
        slug: 'den-duong-jd-8800-150w-p69',
        category: 'den-nlmt',
        brand: 'JD',
        code: 'JD-8800',
        name: 'Đèn đường năng lượng JD-8800 150W',
        price: 1650000,
        image: '../assets/products/den-05.png',
        specs: ['150W', 'Pin LiFePO4', 'BH 2 năm'],
      },
      {
        slug: 'den-pha-nlmt-200w-p70',
        category: 'den-nlmt',
        brand: 'SOLAR',
        code: 'FL-200',
        name: 'Đèn pha năng lượng mặt trời 200W',
        price: 1980000,
        image: '../assets/products/den-06.png',
        specs: ['200W', 'IP66', 'BH 2 năm'],
      },
      {
        slug: 'den-ban-cong-40w-p71',
        category: 'den-nlmt',
        brand: 'BALCONY',
        code: 'BC-40',
        name: 'Đèn ban công năng lượng 40W',
        price: 650000,
        image: '../assets/products/den-07.png',
        specs: ['40W', 'Chống nước', 'BH 2 năm'],
      },
      {
        slug: 'den-cam-bien-80w-p72',
        category: 'den-nlmt',
        brand: 'SENSOR',
        code: 'SN-80',
        name: 'Đèn cảm biến năng lượng 80W',
        price: 1120000,
        image: '../assets/products/den-08.png',
        specs: ['80W', 'PIR', 'BH 2 năm'],
      },
      {
        slug: 'den-duong-jd-7700-100w-p73',
        category: 'den-nlmt',
        brand: 'JD',
        code: 'JD-7700',
        name: 'Đèn đường năng lượng JD-7700 100W',
        price: 1290000,
        image: '../assets/products/den-01.png',
      },
      {
        slug: 'den-pha-nlmt-100w-p74',
        category: 'den-nlmt',
        brand: 'SOLAR',
        code: 'FL-100',
        name: 'Đèn pha năng lượng mặt trời 100W',
        price: 980000,
        image: '../assets/products/den-02.png',
      },
      {
        slug: 'den-tru-san-90w-p75',
        category: 'den-nlmt',
        brand: 'POLE',
        code: 'PL-90',
        name: 'Đèn trụ sân năng lượng 90W',
        price: 1560000,
        image: '../assets/products/den-03.png',
      },
      {
        slug: 'den-tuong-nlmt-50w-p76',
        category: 'den-nlmt',
        brand: 'WALL',
        code: 'WL-50',
        name: 'Đèn tường năng lượng mặt trời 50W',
        price: 720000,
        image: '../assets/products/den-04.png',
      },
      {
        slug: 'den-duong-jd-6600-80w-p77',
        category: 'den-nlmt',
        brand: 'JD',
        code: 'JD-6600',
        name: 'Đèn đường năng lượng JD-6600 80W',
        price: 1050000,
        image: '../assets/products/den-05.png',
      },
      {
        slug: 'den-pha-nlmt-150w-p78',
        category: 'den-nlmt',
        brand: 'SOLAR',
        code: 'FL-150',
        name: 'Đèn pha năng lượng mặt trời 150W',
        price: 1680000,
        image: '../assets/products/den-06.png',
      },
      {
        slug: 'den-san-bong-70w-p79',
        category: 'den-nlmt',
        brand: 'SPORT',
        code: 'SP-70',
        name: 'Đèn sân bóng năng lượng 70W',
        price: 1420000,
        image: '../assets/products/den-07.png',
      },
      {
        slug: 'den-cong-park-110w-p80',
        category: 'den-nlmt',
        brand: 'PARK',
        code: 'PK-110',
        name: 'Đèn công viên năng lượng 110W',
        price: 1750000,
        image: '../assets/products/den-08.png',
      },,
      {
        slug: 'pin-luu-tru-deye-5kwh',
        category: 'pin-luu-tru',
        brand: 'DEYE',
        code: 'DEY-5KWH',
        name: 'Pin lưu trữ Lithium DEYE 5kWh',
        summary: 'Dự phòng điện an toàn, chu kỳ sạc cao.',
        price: 45000000,
        image: 'https://images.unsplash.com/photo-1593941707882-a5bba14938c7?auto=format&fit=crop&w=900&q=85',
        specs: ['Dung lượng 5kWh', 'Chu kỳ cao', 'BH 10 năm'],
        advantages: ['Lưu trữ ổn định', 'An toàn vận hành', 'Mở rộng module dễ dàng'],
        applications: ['Hybrid', 'Off-grid nhẹ', 'Dự phòng mất điện'],
      },
      {
        slug: 'pin-luu-tru-deye-10kwh',
        category: 'pin-luu-tru',
        brand: 'DEYE',
        code: 'DEY-10KWH',
        name: 'Pin lưu trữ Lithium DEYE 10kWh',
        price: 82000000,
        image: 'https://images.unsplash.com/photo-1593941707882-a5bba14938c7?auto=format&fit=crop&w=900&q=85',
        specs: ['10kWh', 'Modular', 'BH 10 năm'],
      },
      {
        slug: 'inverter-solis-5kw',
        category: 'inverter',
        brand: 'SOLIS',
        code: 'SOL-5KW',
        name: 'Inverter hòa lưới SOLIS 5kW',
        summary: 'Ổn định, hiệu quả, dễ giám sát vận hành.',
        price: 18500000,
        image: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?auto=format&fit=crop&w=900&q=85',
        specs: ['Công suất 5kW', 'MPPT kép', 'BH 10 năm'],
        advantages: ['MPPT kép tối ưu sản lượng', 'Giám sát từ xa', 'Tuổi thọ dài'],
        applications: ['Hệ hòa lưới', 'Biệt thự', 'Văn phòng'],
      },
      {
        slug: 'inverter-solis-10kw',
        category: 'inverter',
        brand: 'SOLIS',
        code: 'SOL-10KW',
        name: 'Inverter hòa lưới SOLIS 10kW',
        price: 28900000,
        image: 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?auto=format&fit=crop&w=900&q=85',
        specs: ['10kW', '3 phase', 'BH 10 năm'],
      },
      {
        slug: 'pin-longi-585w',
        category: 'tam-pin',
        brand: 'LONGI',
        code: 'LON-585W',
        name: 'Pin năng lượng mặt trời LONGI 585W',
        summary: 'Hiệu suất cao, tuổi thọ trên 25 năm.',
        price: 3690000,
        compareAt: 4250000,
        discount: 13,
        image: 'https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?auto=format&fit=crop&w=900&q=85',
        specs: ['Công suất 585W', 'Hiệu suất cao', 'BH 25 năm'],
        advantages: ['Hiệu suất chuyển đổi cao', 'Chịu tải cơ học tốt', 'Phù hợp mái nhà & nhà xưởng'],
        applications: ['Hộ gia đình', 'Doanh nghiệp', 'Nhà xưởng'],
      },
      {
        slug: 'pin-longi-550w',
        category: 'tam-pin',
        brand: 'LONGI',
        code: 'LON-550W',
        name: 'Tấm pin năng lượng LONGI 550W',
        price: 3350000,
        image: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?auto=format&fit=crop&w=900&q=85',
        specs: ['550W', 'Mono PERC', 'BH 25 năm'],
      },
      {
        slug: 'cap-dc-cadivi',
        category: 'phu-kien',
        brand: 'CADIVI',
        code: 'CAD-DC46',
        name: 'Cáp điện DC solar CADIVI',
        summary: 'Chịu UV ngoài trời, đạt chuẩn kỹ thuật.',
        price: 890000,
        image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=900&q=85',
        specs: ['Tiết diện 4–6mm²', 'Chịu UV ngoài trời', 'Chuẩn TCVN'],
        advantages: ['Chịu nhiệt & UV', 'Độ bền cao', 'Dễ thi công'],
        applications: ['Kết nối tấm pin', 'Inverter', 'Tủ DC'],
      },
      {
        slug: 'khung-gia-do-vrock',
        category: 'phu-kien',
        brand: 'VROCK',
        code: 'VRO-FRAME',
        name: 'Khung giá đỡ tấm pin VROCK',
        summary: 'Kết cấu nhôm chắc chắn, chịu gió bão tốt.',
        price: 1250000,
        image: 'https://images.unsplash.com/photo-1559302504-64aae6ca6b6d?auto=format&fit=crop&w=900&q=85',
        specs: ['Nhôm hợp kim', 'Chịu gió bão', 'BH 15 năm'],
        advantages: ['Chống ăn mòn', 'Lắp đặt linh hoạt', 'Tuổi thọ dài'],
        applications: ['Mái tôn', 'Mái bằng', 'Khung ground-mount'],
      },
      {
        slug: 'tu-dien-suntree',
        category: 'thiet-bi-dien',
        brand: 'SUNTREE',
        code: 'SUN-DCAC',
        name: 'Tủ điện DC/AC SUNTREE',
        summary: 'Bảo vệ hệ thống chuyên nghiệp, chuẩn outdoor.',
        price: 3200000,
        image: 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?auto=format&fit=crop&w=900&q=85',
        specs: ['Bảo vệ quá tải', 'IP65 ngoài trời', 'BH 5 năm'],
        advantages: ['Chuẩn outdoor IP65', 'Lắp đặt nhanh', 'Bảo vệ toàn diện'],
        applications: ['Hệ áp mái', 'Nhà xưởng', 'Trạm biến áp nhỏ'],
      },
      {
        slug: 'cb-dc-suntree',
        category: 'thiet-bi-dien',
        brand: 'SUNTREE',
        code: 'SUN-CB',
        name: 'CB DC bảo vệ hệ thống SUNTREE',
        price: 780000,
        image: 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?auto=format&fit=crop&w=900&q=85',
        specs: ['DC breaker', 'Outdoor', 'BH 3 năm'],
      },
    ],
  },
  projects: {
    label: 'DỰ ÁN',
    title: ['DỰ ÁN ', 'ĐÃ THỰC HIỆN'],
    titleAccentIndex: 1,
    desc: '',
    catalogHref: 'du-an/',
    bg: {
      src: '../assets/backgrounds/bg-section-04-projects.png',
      overlay: 0.78,
      tone: 'sky',
      pattern: 'none',
    },
    items: [
      {
        slug: 'biet-thu-binh-duong',
        cat: 'HỆ THỐNG ĐIỆN MẶT TRỜI',
        title: 'Nhà máy ABC',
        summary: 'Hệ áp mái tối ưu cho biệt thự, tiết kiệm điện bền vững.',
        power: '120 kWp',
        place: 'Bình Dương',
        year: '2024',
        area: '180m²',
        system: 'Hòa lưới',
        image: 'https://images.unsplash.com/photo-1613665813446-82a78c468a1d?auto=format&fit=crop&w=1600&q=85',
        gallery: [
          'https://images.unsplash.com/photo-1613665813446-82a78c468a1d?auto=format&fit=crop&w=1200&q=85',
          'https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?auto=format&fit=crop&w=1200&q=85',
          'https://images.unsplash.com/photo-1497440001374-f26997328c1b?auto=format&fit=crop&w=1200&q=85',
        ],
        process: ['Khảo sát mái', 'Thiết kế hệ thống', 'Thi công lắp đặt', 'Nghiệm thu bàn giao'],
        specs: ['Công suất 120 kWp', 'Inverter hòa lưới', 'BH tấm pin 25 năm'],
        video: '',
      },
      {
        slug: 'nha-xuong-long-an',
        cat: 'HỆ THỐNG ĐIỆN MẶT TRỜI',
        title: 'Nhà xưởng Long An',
        summary: 'Giải pháp công suất lớn cho nhà xưởng sản xuất.',
        power: '500 kWp',
        place: 'Long An',
        year: '2023',
        area: '1200m²',
        system: 'Hybrid',
        image: 'https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?auto=format&fit=crop&w=1600&q=85',
        gallery: [
          'https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?auto=format&fit=crop&w=1200&q=85',
          'https://images.unsplash.com/photo-1559302504-64aae6ca6b6d?auto=format&fit=crop&w=1200&q=85',
          'https://images.unsplash.com/photo-1509391366360-2e959784a276?auto=format&fit=crop&w=1200&q=85',
        ],
        process: ['Khảo sát kết cấu', 'Thiết kế tối ưu tải', 'Thi công theo phase', 'Nghiệm thu & giám sát'],
        specs: ['Công suất 500 kWp', 'Hệ hybrid', 'Giám sát từ xa'],
        video: '',
      },
      {
        slug: 'trung-tam-thuong-mai-tphcm',
        cat: 'HỆ THỐNG ĐIỆN MẶT TRỜI',
        title: 'TTTM TP. Hồ Chí Minh',
        summary: 'Hệ thống quy mô lớn, vận hành ổn định cho TTTM.',
        power: '1.2 MWp',
        place: 'TP. Hồ Chí Minh',
        year: '2024',
        area: '8500m²',
        system: 'Hòa lưới',
        image: 'https://images.unsplash.com/photo-1559302504-64aae6ca6b6d?auto=format&fit=crop&w=1600&q=85',
        gallery: [
          'https://images.unsplash.com/photo-1559302504-64aae6ca6b6d?auto=format&fit=crop&w=1200&q=85',
          'https://images.unsplash.com/photo-1466611653911-95081537e5b7?auto=format&fit=crop&w=1200&q=85',
        ],
        process: ['Khảo sát hiện trường', 'Thiết kế kỹ thuật', 'Thi công & QC', 'Bàn giao vận hành'],
        specs: ['Công suất 1.2 MWp', 'Đa inverter', 'Bảo trì định kỳ'],
        video: '',
      },
      {
        slug: 'trang-trai-tay-ninh',
        cat: 'HỆ THỐNG ĐIỆN MẶT TRỜI',
        title: 'Trang trại Tây Ninh',
        summary: 'Điện mặt trời hỗ trợ vận hành trang trại bền vững.',
        power: '200 kWp',
        place: 'Tây Ninh',
        year: '2022',
        area: '3200m²',
        system: 'Hòa lưới',
        image: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?auto=format&fit=crop&w=1600&q=85',
        gallery: [
          'https://images.unsplash.com/photo-1509391366360-2e959784a276?auto=format&fit=crop&w=1200&q=85',
          'https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?auto=format&fit=crop&w=1200&q=85',
        ],
        process: ['Khảo sát địa hình', 'Thiết kế ground-mount', 'Thi công khung & pin', 'Kết nối lưới'],
        specs: ['Công suất 200 kWp', 'Ground mount', 'Chống ăn mòn cao'],
        video: '',
      },
      {
        slug: 'kho-hang-dong-nai',
        cat: 'HỆ THỐNG ĐIỆN MẶT TRỜI',
        title: 'Kho hàng Đồng Nai',
        summary: 'Hệ áp mái tối ưu chi phí điện cho kho logistics.',
        power: '350 kWp',
        place: 'Đồng Nai',
        year: '2024',
        area: '2800m²',
        system: 'Hòa lưới',
        image: 'https://images.unsplash.com/photo-1497440001374-f26997328c1b?auto=format&fit=crop&w=1600&q=85',
        gallery: [
          'https://images.unsplash.com/photo-1497440001374-f26997328c1b?auto=format&fit=crop&w=1200&q=85',
          'https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?auto=format&fit=crop&w=1200&q=85',
        ],
        process: ['Khảo sát mái kho', 'Thiết kế tải gió', 'Thi công lắp đặt', 'Nghiệm thu'],
        specs: ['Công suất 350 kWp', 'Inverter chuỗi', 'BH tấm pin 25 năm'],
        video: '',
      },
    ],
  },
  services: {
    label: 'DỊCH VỤ',
    title: ['DỊCH VỤ HỆ THỐNG ', 'ĐIỆN MẶT TRỜI'],
    titleAccentIndex: 1,
    desc: 'ĐỒNG HÀNH CÙNG BẠN TỪ KHÂU TƯ VẤN ĐẾN VẬN HÀNH HỆ THỐNG',
    catalogHref: 'dich-vu/',
    bg: {
      src: '../assets/backgrounds/bg-section-05-services.png',
      overlay: 0.72,
      tone: 'sky',
      pattern: 'none',
    },
    steps: [
      {
        slug: 'thi-cong-lap-dat',
        num: '01',
        title: 'Thi công lắp đặt',
        text: 'Triển khai đúng tiêu chuẩn kỹ thuật, đảm bảo an toàn và đúng tiến độ.',
        icon: 'build',
        image: 'https://images.unsplash.com/photo-1613665813446-82a78c468a1d?auto=format&fit=crop&w=1200&q=85',
        process: ['Lắp khung giá đỡ', 'Lắp tấm pin & inverter', 'Kết nối điện'],
        advantages: ['An toàn lao động', 'Đúng tiến độ', 'QC từng hạng mục'],
      },
      {
        slug: 'thiet-ke-he-thong',
        num: '02',
        title: 'Tư vấn & thiết kế',
        text: 'Thiết kế tối ưu công suất, bố trí thiết bị và mô phỏng sản lượng điện.',
        icon: 'design',
        image: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&w=1200&q=85',
        process: ['Mô phỏng sản lượng', 'Bố trí thiết bị', 'Hồ sơ kỹ thuật'],
        advantages: ['Thiết kế chuẩn', 'Tối ưu hiệu suất', 'Dễ thi công'],
      },
      {
        slug: 'bao-tri-dinh-ky',
        num: '03',
        title: 'Bảo trì & vệ sinh',
        text: 'Kiểm tra, vệ sinh và tối ưu hiệu suất hoạt động của hệ thống.',
        icon: 'maintain',
        image: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?auto=format&fit=crop&w=1200&q=85',
        process: ['Vệ sinh tấm pin', 'Kiểm tra thiết bị', 'Báo cáo hiệu suất'],
        advantages: ['Duy trì sản lượng', 'Phát hiện sớm sự cố', 'Kéo dài tuổi thọ'],
      },
      {
        slug: 'ho-tro-ky-thuat',
        num: '04',
        title: 'Giám sát & vận hành',
        text: 'Theo dõi hiệu suất, xử lý sự cố và đồng hành vận hành lâu dài.',
        icon: 'monitor',
        image: 'https://images.unsplash.com/photo-1556745753-b2904692b3cd?auto=format&fit=crop&w=1200&q=85',
        process: ['Giám sát từ xa', 'Cảnh báo sự cố', 'Tối ưu vận hành'],
        advantages: ['Phản hồi nhanh', 'Minh bạch số liệu', 'Đồng hành lâu dài'],
      },
      {
        slug: 'khao-sat-cong-trinh',
        num: '05',
        title: 'Khảo sát công trình',
        text: 'Đánh giá hiện trạng, hướng nắng và kết cấu để đưa ra phương án phù hợp.',
        icon: 'search',
        image: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?auto=format&fit=crop&w=1200&q=85',
        process: ['Khảo sát hiện trường', 'Đo đạc & phân tích', 'Đề xuất phương án'],
        advantages: ['Chính xác kỹ thuật', 'Tối ưu công suất', 'Phù hợp ngân sách'],
      },
      {
        slug: 'nghiem-thu-ban-giao',
        num: '06',
        title: 'Nghiệm thu bàn giao',
        text: 'Kiểm tra toàn bộ hệ thống, hướng dẫn vận hành và bàn giao hoàn chỉnh.',
        icon: 'check',
        image: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=1200&q=85',
        process: ['Kiểm tra vận hành', 'Hướng dẫn sử dụng', 'Bàn giao hồ sơ'],
        advantages: ['Minh bạch', 'Đầy đủ hồ sơ', 'Sẵn sàng vận hành'],
      },
    ],
    ctaTitle: 'Bạn cần tư vấn giải pháp điện mặt trời?',
    ctaDesc: 'Đội ngũ Solar Miền Nam luôn sẵn sàng khảo sát và tư vấn giải pháp phù hợp cho công trình của bạn.',
    ctaBtn: 'NHẬN BÁO GIÁ MIỄN PHÍ',
  },
  news: {
    label: 'TIN TỨC',
    title: ['TIN ', 'TỨC'],
    titleAccentIndex: 1,
    desc: 'Cập nhật xu hướng, kiến thức và giải pháp năng lượng mới nhất',
    catalogHref: 'tin-tuc/',
    bg: {
      src: '../assets/backgrounds/bg-section-06-news.png',
      overlay: 0.86,
      tone: 'mist-white',
      pattern: 'blueprint',
    },
    items: [
      {
        slug: '5-loi-ich-doanh-nghiep-dien-mat-troi',
        cat: 'NỔI BẬT',
        featured: true,
        date: '30/06/2024',
        datetime: '2024-06-30',
        title: '5 lợi ích khi doanh nghiệp đầu tư hệ thống điện mặt trời',
        excerpt: 'Khám phá những lợi ích vượt trội giúp doanh nghiệp tối ưu chi phí và phát triển bền vững.',
        image: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?auto=format&fit=crop&w=1600&q=85',
        content: [
          'Đầu tư điện mặt trời giúp doanh nghiệp giảm chi phí điện vận hành và tăng chủ động năng lượng.',
          'Hệ thống còn nâng cao hình ảnh doanh nghiệp xanh, đáp ứng yêu cầu ESG và phát triển bền vững.',
          'Với chính sách bảo hành dài hạn, đây là khoản đầu tư có lộ trình hoàn vốn rõ ràng.',
        ],
      },
      {
        slug: 'huong-dan-bao-tri-he-thong-dien-mat-troi',
        cat: 'HƯỚNG DẪN',
        date: '28/06/2024',
        datetime: '2024-06-28',
        title: 'Hướng dẫn bảo trì hệ thống điện mặt trời hiệu quả',
        excerpt: 'Các bước vệ sinh và kiểm tra an toàn giúp kéo dài tuổi thọ hệ thống.',
        image: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?auto=format&fit=crop&w=1200&q=85',
        content: [
          'Bụi bẩn và lá cây bám trên tấm pin có thể làm giảm sản lượng nếu không được vệ sinh định kỳ.',
          'Nên kiểm tra khung giá đỡ, đầu nối DC và tình trạng inverter theo lịch bảo trì khuyến nghị.',
        ],
      },
      {
        slug: 'xu-huong-nang-luong-xanh-2024',
        cat: 'TIN TỨC',
        date: '25/06/2024',
        datetime: '2024-06-25',
        title: 'Xu hướng năng lượng xanh trong năm 2024',
        excerpt: 'Cập nhật xu hướng chuyển đổi năng lượng sạch tại Việt Nam.',
        image: 'https://images.unsplash.com/photo-1466611653911-95081537e5b7?auto=format&fit=crop&w=1200&q=85',
        content: [
          'Năng lượng xanh tiếp tục là ưu tiên của nhiều doanh nghiệp nhờ thời gian hoàn vốn rõ ràng.',
          'Công nghệ tấm pin hiệu suất cao và inverter thông minh giúp theo dõi sản lượng dễ dàng hơn.',
        ],
      },
      {
        slug: 'chi-phi-lap-dat-dien-mat-troi-2024',
        cat: 'KIẾN THỨC',
        date: '20/06/2024',
        datetime: '2024-06-20',
        title: 'Chi phí lắp đặt điện mặt trời mới nhất 2024',
        excerpt: 'Tổng hợp khoảng chi phí đầu tư phổ biến theo quy mô công trình.',
        image: 'https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?auto=format&fit=crop&w=1200&q=85',
        content: [
          'Chi phí lắp đặt phụ thuộc công suất, loại tấm pin, inverter và điều kiện mái nhà.',
          'Khảo sát hiện trường giúp báo giá chính xác và tối ưu phương án đầu tư.',
        ],
      },
      {
        slug: 'cach-chon-cong-suat-he-thong',
        cat: 'KIẾN THỨC',
        date: '01/08/2026',
        datetime: '2026-08-01',
        title: 'Cách chọn công suất hệ thống điện mặt trời phù hợp cho gia đình',
        excerpt: 'Hướng dẫn tính toán nhu cầu tiêu thụ và chọn công suất tấm pin, inverter để tối ưu chi phí đầu tư.',
        image: 'https://images.unsplash.com/photo-1497440001374-f26997328c1b?auto=format&fit=crop&w=1200&q=85',
        content: [
          'Việc chọn đúng công suất hệ thống điện mặt trời giúp tối ưu chi phí đầu tư và đáp ứng nhu cầu sử dụng điện thực tế của gia đình.',
          'Bước đầu tiên là thống kê hóa đơn điện 6–12 tháng gần nhất, từ đó ước lượng mức tiêu thụ trung bình mỗi ngày.',
        ],
      },
      {
        slug: 'uu-dai-lap-dat-he-thong-gia-dinh',
        cat: 'ƯU ĐÃI',
        date: '28/06/2026',
        datetime: '2026-06-28',
        title: 'Ưu đãi lắp đặt hệ thống điện mặt trời cho hộ gia đình',
        excerpt: 'Chương trình hỗ trợ khảo sát miễn phí và chính sách bảo hành dài hạn cho khách hàng mới.',
        image: 'https://images.unsplash.com/photo-1559302504-64aae6ca6b6d?auto=format&fit=crop&w=1200&q=85',
        content: [
          'Solar Miền Nam triển khai chương trình ưu đãi dành cho hộ gia đình lắp đặt hệ thống điện mặt trời trong quý này.',
          'Khách hàng được khảo sát hiện trường miễn phí, tư vấn công suất và nhận báo giá minh bạch theo từng hạng mục.',
        ],
      },
    ],
  },
  testimonials: {
    titleBefore: 'KHÁCH HÀNG ',
    titleAccent: 'NÓI GÌ',
    titleAfter: ' VỀ CHÚNG TÔI',
    bg: {
      src: '../assets/backgrounds/bg-section-04-projects.png',
      overlay: 0.88,
      tone: 'mist-white',
      pattern: 'solar-grid',
    },
    items: [
      {
        image: 'https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?auto=format&fit=crop&w=900&q=85',
        quote: 'Hệ thống điện mặt trời được thi công chuyên nghiệp, đúng tiến độ. Hiệu suất hoạt động ổn định, giúp công ty tiết kiệm chi phí điện đáng kể.',
        name: 'Anh Minh Tuấn',
        role: 'Giám đốc - Công ty TNHH Minh Tuấn',
        avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=200&q=80',
        rating: 5,
      },
      {
        image: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?auto=format&fit=crop&w=900&q=85',
        quote: 'Từ khâu tư vấn đến lắp đặt đều rất tận tâm. Hệ thống vận hành hiệu quả, đội ngũ hỗ trợ nhanh chóng mỗi khi cần.',
        name: 'Anh Quốc Bảo',
        role: 'Giám đốc - Công ty CP Quốc Bảo',
        avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80',
        rating: 5,
      },
      {
        image: 'https://images.unsplash.com/photo-1497440001374-f26997328c1b?auto=format&fit=crop&w=900&q=85',
        quote: 'Chất lượng thiết bị tốt, thi công an toàn, đúng kỹ thuật. Chúng tôi hoàn toàn hài lòng và sẽ tiếp tục đồng hành lâu dài.',
        name: 'Anh Hoàng Nam',
        role: 'Quản lý vận hành - Nhà máy Hoàng Nam',
        avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=200&q=80',
        rating: 5,
      },
      {
        image: 'https://images.unsplash.com/photo-1613665813446-82a78c468a1d?auto=format&fit=crop&w=900&q=85',
        quote: 'Báo giá minh bạch, khảo sát kỹ lưỡng. Sau 6 tháng vận hành, sản lượng điện đúng như cam kết ban đầu.',
        name: 'Chị Thu Hà',
        role: 'Chủ đầu tư - Biệt thự Bình Dương',
        avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
        rating: 5,
      },
      {
        image: 'https://images.unsplash.com/photo-1559302504-64aae6ca6b6d?auto=format&fit=crop&w=900&q=85',
        quote: 'Đội ngũ kỹ thuật chuyên nghiệp, bảo trì định kỳ chu đáo. Rất yên tâm khi gửi gắm hệ thống cho Solar Miền Nam.',
        name: 'Anh Đức Anh',
        role: 'Giám đốc kỹ thuật - Kho logistics Đồng Nai',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
        rating: 5,
      },
    ],
  },
  contact: {
    label: 'LIÊN HỆ',
    title: ['SẴN SÀNG ĐỒNG HÀNH', 'CÙNG DỰ ÁN CỦA BẠN'],
    desc: 'Để lại thông tin để được khảo sát miễn phí và nhận tư vấn giải pháp điện mặt trời phù hợp công trình của bạn.',
    bg: '../assets/backgrounds/bg-section-07-contact.png',
    phone: '0938 961 012',
    phoneTel: '0938961012',
    email: 'info@solarmiennam.vn',
    address: 'Số 12 Nguyễn Văn Linh, Quận 7, TP. Hồ Chí Minh',
    website: 'www.solarmiennam.vn',
    zalo: 'https://zalo.me/0938961012',
    hours: 'Thứ 2 – Thứ 7: 8:00 – 17:30',
    benefits: [
      'Khảo sát miễn phí',
      'Báo giá nhanh trong 24 giờ',
      'Tư vấn giải pháp tối ưu',
      'Bảo hành chính hãng',
    ],
    socials: {
      facebook: 'https://facebook.com',
      zalo: 'https://zalo.me/0938961012',
      youtube: 'https://youtube.com',
    },
    form: {
      title: 'ĐĂNG KÝ NHẬN TƯ VẤN',
      projectTypes: ['Nhà phố', 'Biệt thự', 'Nhà xưởng', 'Doanh nghiệp', 'Khác'],
      needs: ['Lắp điện mặt trời', 'Inverter', 'Pin lưu trữ', 'Bảo trì', 'Khảo sát', 'Khác'],
      consent: 'Tôi đồng ý để Solar Miền Nam liên hệ tư vấn.',
      submit: 'GỬI YÊU CẦU TƯ VẤN',
      successTitle: 'Cảm ơn Quý khách.',
      successDesc: 'Solar Miền Nam sẽ liên hệ trong thời gian sớm nhất.',
    },
  },
  footer: {
    about: 'Solar Miền Nam chuyên cung cấp giải pháp điện năng lượng mặt trời và hệ thống chiếu sáng LED cho hộ gia đình, doanh nghiệp và nhà xưởng.',
    productLinks: [
      { label: 'Pin năng lượng mặt trời', href: 'san-pham/pin-longi-585w/' },
      { label: 'Inverter', href: 'san-pham/inverter-solis-5kw/' },
      { label: 'Pin lưu trữ', href: 'san-pham/pin-luu-tru-deye-5kwh/' },
      { label: 'Tủ điện', href: 'san-pham/tu-dien-suntree/' },
    ],
    serviceLinks: [
      { label: 'Khảo sát công trình', href: 'dich-vu/khao-sat-cong-trinh/' },
      { label: 'Thiết kế hệ thống', href: 'dich-vu/thiet-ke-he-thong/' },
      { label: 'Thi công lắp đặt', href: 'dich-vu/thi-cong-lap-dat/' },
      { label: 'Bảo trì định kỳ', href: 'dich-vu/bao-tri-dinh-ky/' },
    ],
  },
};
